# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ArcoScribeApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Add this section to copy vector icon fonts
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-vector-icons'
        target.build_phases.each do |build_phase|
          if build_phase.respond_to?(:name) && build_phase.name == '[CP] Copy Pods Resources'
            fonts = Dir[File.join(config[:reactNativePath], '../node_modules/react-native-vector-icons/Fonts/*.ttf')]
            build_phase.input_paths.concat(fonts)
          end
        end
      end
    end
  end
end
